<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="20" verbose="0" name="Failed suite [FunctionalTests]" parallel="methods">
  <parameter name="resultSin" value="0.8414709848078965"/>
  <parameter name="resultPow" value="25"/>
  <parameter name="resultCos" value="0.5403023058681398"/>
  <parameter name="resultSqrt" value="3"/>
  <parameter name="numberSqrt" value="9"/>
  <parameter name="numberSin" value="1"/>
  <parameter name="numberCos" value="1"/>
  <parameter name="numberPow1" value="5"/>
  <parameter name="numberPow2" value="2"/>
  <listeners>
    <listener class-name="com.epam.calculator.listener.MethodListener"/>
    <listener class-name="com.epam.calculator.listener.TestListener"/>
  </listeners>
  <test name="TestNG Functional Group(failed)" parallel="methods">
    <parameter name="resultSin" value="0.8414709848078965"/>
    <parameter name="resultPow" value="25"/>
    <parameter name="resultCos" value="0.5403023058681398"/>
    <parameter name="resultSqrt" value="3"/>
    <parameter name="numberSqrt" value="9"/>
    <parameter name="numberSin" value="1"/>
    <parameter name="numberCos" value="1"/>
    <parameter name="numberPow1" value="5"/>
    <parameter name="numberPow2" value="2"/>
    <groups>
      <run>
        <include name="functional"/>
      </run>
    </groups>
    <classes>
      <class name="com.epam.calculator.testCalculator.baseOperations.TestMult">
        <methods>
          <include name="afterTest"/>
          <include name="beforeTest"/>
          <include name="testMultExceptionIsThrown" invocation-numbers="3 2 0 1"/>
        </methods>
      </class> <!-- com.epam.calculator.testCalculator.baseOperations.TestMult -->
      <class name="com.epam.calculator.testCalculator.baseOperations.TestSub">
        <methods>
          <include name="testSubExceptionIsThrown" invocation-numbers="0 1 3 5 7 2 4 6"/>
        </methods>
      </class> <!-- com.epam.calculator.testCalculator.baseOperations.TestSub -->
      <class name="com.epam.calculator.testCalculator.baseOperations.TestSum">
        <methods>
          <include name="testSumExceptionIsThrown" invocation-numbers="2 4 6 8 1 0 7 5 3 9"/>
        </methods>
      </class> <!-- com.epam.calculator.testCalculator.baseOperations.TestSum -->
    </classes>
  </test> <!-- TestNG Functional Group(failed) -->
</suite> <!-- Failed suite [FunctionalTests] -->
